#!/usr/bin/env bash

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

if ! grep -qs "recommended by brew doctor" ~/.bashrc; then
  fancy_echo "Put Homebrew location earlier in PATH ..."
    successfully echo "\n# recommended by brew doctor" >> ~/.bashrc
    successfully echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.bashrc
    successfully source ~/.bashrc
fi

fancy_echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
  successfully brew install the_silver_searcher

fancy_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  successfully brew install tmux

fancy_echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  successfully brew install imagemagick

fancy_echo "Installing GNU Compiler Collection, a necessary prerequisite to installing Ruby ..."
  successfully brew tap homebrew/dupes
  successfully brew install apple-gcc42

fancy_echo "Installing rvm with ruby-2.0.0"
  succesfully curl -L https://get.rvm.io | bash -s stable --ruby=2.0.0

fancy_echo "Updating to latest Rubygems version ..."
  successfully gem update --system

fancy_echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman pg rails thin --no-document

if ! grep -qs "DO NOT EDIT BELOW THIS LINE" ~/.bashrc; then
  fancy_echo "Prepare ~/.bashrc for http://github.com/thoughtbot/dotfiles ..."
    successfully echo "# DO NOT EDIT BELOW THIS LINE\n" >> ~/.bashrc
fi
